dist: trusty
language: java
jdk:
 - openjdk13

addons:
  sonarcloud:
    organization: "cayden10"
    token:
      secure: "ed0921aab6a9a7d74f56939441db8e1faf068404"


script: 
-ant build
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=cayden10_Project1